# EXECUTE O SCRIPT E LEIA OS COMENTÁRIOS PARA UM MELHOR ENTENDIMENTO DE COMO FUNCIONA A BIBLIOTECA 'matriz'

# IMPORTANDO A BIBLIOTECA.
from matriz import matriz

# A BIBLIOTECA TEM UMA ÚNICA SIMPLES FUNCIONALIDADE GERAR MATRIZES.

# VARIÁVEL "A" RECEBENDO A CLASSE MATRIZ.
A = matriz()

# GERANDO A MATRIZ INFORMANDO QUANTIDADE DE LINHAS E COLUNAS.
print('GERANDO A MATRIZ')
matriz_de_A = A.GerarMatriz(2, 4)

# USE O PRINT PARA ANALISAR COMO FICA A MATRIZ GERADA.
print('MÉTODO "matriz_de_A = A.GerarMatriz(2, 4)".')
print(matriz_de_A)


# OBS: APÓS GERAR A MATRIZ VOCÊ TAMBÉM PODE COLOCAR A MATRIZ EM UMA VARIÁVEL DA SEGUINTE FORMA.
matriz_de_A = A.matriz

# USE O PRINT PARA ANALISAR COMO FICA A MATRIZ GERADA.
print('MÉTODO "matriz_de_A = A.matriz", OBS: SÓ É VÁLIDO DESTA FORMA APÓS JÁ TER UTILIZADO A FUNÇÃO PARA GERAR A MATRIZ.')
print(matriz_de_A)

# O MESMO VALE PARA A QUANTIDADE DE LINHAS E COLUNAS.
linhas_de_A = A.linhas
colunas_de_A = A.colunas

print(f'LINHAS: {linhas_de_A}, COLUNAS: {colunas_de_A}')

# FIM DO EXEMPLO DE USO.